[pytest]
DJANGO_SETTINGS_MODULE = cooldeal.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov --cov-report=html --cov-report=term-missing --html=report.html --self-contained-html
testpaths = tests
markers =
    unit: Tests unitaires pour les modèles et les méthodes isolées.
    integration: Tests d'intégration pour les vues, URLs et templates.
    functional: Tests fonctionnels simulant des parcours utilisateur.